name: Report a Bug
description: You found a bug within Zammad? Use this to let us know, please ensure to fill in the complete template! - NO TECHNICAL QUESTIONS
labels: ['needs verification']
body:
  - type: markdown
    attributes:
      value: |
        Hi there - thanks for filing an issue. Please ensure the following things before creating an issue - thank you! 🤓

        🛑 Please posts the following on our community board (https://community.zammad.org/):

        👉 Feature Requests
        👉 Development Questions
        👉 Technical Questions (assistance for non paid / community)

        If you think you hit a bug, please continue:

        👉 Search existing issues and the CHANGELOG.md for your issue - there might be a solution already
        👉 Make sure to use the latest version of Zammad if possible
        👉 Add the `log/production.log` file from your system. Attention: Make sure no confidential data is in it!
        👉 Please write the issue in english
        👉 Don't remove the template - otherwise we will close the issue without further comments
        👉 Ask questions about Zammad configuration and usage at our mailinglist. See: https://zammad.org/participate

        Note: We always do our best. Unfortunately, sometimes there are too many requests and we can't handle everything at once. If you want to prioritize/escalate your issue, you can do so by means of a support contract (see https://zammad.com/pricing#selfhosted).
  - type: input
    id: bug-used-zammad-version
    attributes:
      label: Used Zammad Version
      placeholder: 5.3
    validations:
      required: true
  - type: input
    id: bug-installation-method
    attributes:
      label: Installation method
      placeholder: source, package, ...
    validations:
      required: true
  - type: input
    id: bug-operation-system
    attributes:
      label: Operating system
      description: When you're unsure, use `cat /etc/os-release`.
      placeholder: source, package, ...
    validations:
      required: true
  - type: input
    id: bug-installation-method
    attributes:
      label: Installation method
      placeholder: source, package, ...
    validations:
      required: true
  - type: textarea
    id: bug-actual-behaviour
    attributes:
      label: Actual behaviour
      description: Describe the actual behaviour.
    validations:
      required: true
  - type: textarea
    id: bug-expected-behaviour
    attributes:
      label: Expected behaviour
      description: Describe the expected behaviour.
    validations:
      required: true
  - type: textarea
    id: bug-steps-reproduction
    attributes:
      label: Steps to reproduce the behaviour
    validations:
      required: true
  - type: checkboxes
    id: bug-confirm
    attributes:
      label: Yes I'm sure this is a bug and no feature request or a general question.
    validations:
      required: true
